apiVersion: keda.sh/v1alpha1
kind: ScaledObject # в тз указано распределение нагрузки по времени суток, поэтому оптимально использовать KEDA (главное не забыть его установить в наш кластер)
metadata:
  name: nginx-app-cron-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: nginx-app
  pollingInterval: 30          
  cooldownPeriod: 300 # откат вниз через 5 минут после отсутствия триггера
  minReplicaCount: 1 # ночью
  maxReplicaCount: 4 # взято в соответствии с ТЗ, однако я бы поставил 5 или 6 на случай неожиданных и непредусмотренных пиков (резкий наплыв пользователей, DDoS и тд), чтобы в случае происшествия было время на реакцию без аффекта на потребителя
  triggers: 
    - type: cron # пользуемся кроном для управлением ресурсами по расписанию 
      metadata:
        timezone: "Europe/Moscow"
        start: "07:00"
        end: "22:00"
        desiredReplicas: "2" # тут я взял не максимальное количество, рассчитанное на пиковую нагрузку (4), чтобы не было простоя мощностей - при их недостатке триггер CPU позволит автоскейлить до нужного количества под 
    - type: cron
      metadata:
        timezone: "Europe/Moscow"
        start: "22:01"
        end: "06:59"
        desiredReplicas: "1"
    - type: cpu # для оптимизации количества используемых ресурсов также смотрим на потребляемые процессорные мощности, чтобы в дневное время не держать постоянно максимальное количество подов
      metadata:
        type: Utilization
        value: "70"
